module.exports = {
  SECRET: "SECRET",
  MONGO_USER: "MONGO_USER",
  MONGO_PASS: "MONGO_PASS",
  MONGO_CLUSTER: "MONGO_CLUSTER",
  SESSION_SECRET: "SESSION_SECRET",
  MAIL_EMAIL: "MAIL_EMAIL",
  MAIL_PASS: "MAIL_PASS",
  ALLOW_USER_CREATION: true
};